name: Automated Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        python-version: [3.12]


    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest checkout version

    - name: Set up Python
      uses: actions/setup-python@v4  # Use the latest setup-python version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || echo "No requirements file found"

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s . -p "test_*.py"

